# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: circles-indexer
field_selection:
  transaction_fields:
    - hash
    - transactionIndex
contracts:
- name: Hub
  handler: src/EventHandlers.ts
  events:
  - event: HubTransfer(address indexed from, address indexed to, uint256 amount)
  - event: OrganizationSignup(address indexed organization)
  - event: Signup(address indexed user, address token)
  - event: Trust(address indexed canSendTo, address indexed user, uint256 limit)
- name: PersonalCRC
  abi_file_path: abis/PersonalCRC.json
  handler: src/EventHandlers.ts
  events:
  - event: Transfer(address indexed from, address indexed to, uint256 amount)
- name: HubV2
  handler: src/EventHandlers.ts
  events:
  - event: RegisterHuman(address indexed avatar)
  - event: InviteHuman(address indexed inviter, address indexed invited)
  - event: RegisterOrganization(address indexed organization, string name)
  - event: RegisterGroup(address indexed group, address indexed mint, address indexed treasury, string name, string symbol)
  - event: Trust(address indexed truster, address indexed trustee, uint256 expiryTime)
  - event: Stopped(address indexed avatar)
  - event: StreamCompleted(address indexed operator, address indexed from, address indexed to, uint256[] ids, uint256[] amounts)
  - event: ApprovalForAll(address indexed account, address indexed operator, bool approved)
  - event: PersonalMint(address indexed human, uint256 amount, uint256 period, uint256 endPeriod)
  - event: TransferSingle(address indexed operator, address indexed from, address indexed to, uint256 id, uint256 value)
  - event: TransferBatch(address indexed operator, address indexed from, address indexed to, uint256[] ids, uint256[] values)
  - event: URI(string value, uint256 indexed id)
- name: ERC20Lift
  handler: src/EventHandlers.ts
  events:
  - event: ProxyCreation(address proxy, address masterCopy)
  - event: ERC20WrapperDeployed(address indexed avatar, address indexed erc20Wrapper, uint8 circlesType)
- name: StandardTreasury
  handler: src/EventHandlers.ts
  events:
  - event: CreateVault(address indexed group, address indexed vault)
  - event: GroupMintSingle(address indexed group, uint256 indexed id, uint256 value, bytes userData)
  - event: GroupMintBatch(address indexed group, uint256[] ids, uint256[] values, bytes userData)
  - event: GroupRedeem(address indexed group, uint256 indexed id, uint256 value, bytes data)
  - event: GroupRedeemCollateralReturn(address indexed group, address indexed to, uint256[] ids, uint256[] values)
  - event: GroupRedeemCollateralBurn(address indexed group, uint256[] ids, uint256[] values)
- name: NameRegistry
  handler: src/EventHandlers.ts
  events:
  - event: UpdateMetadataDigest(address indexed avatar, bytes32 metadataDigest)
- name: WrapperERC20Personal
  handler: src/EventHandlers.ts
  events:
  - event: Transfer(address indexed from, address indexed to, uint256 value)
  - event: DepositDemurraged(address indexed account, uint256 amount, uint256 inflationaryAmount)
  - event: WithdrawDemurraged(address indexed account, uint256 amount, uint256 inflationaryAmount)
  - event: DepositInflationary(address indexed account, uint256 amount, uint256 demurragedAmount)
  - event: WithdrawInflationary(address indexed account, uint256 amount, uint256 demurragedAmount)
- name: SafeAccount
  handler: src/EventHandlers.ts
  events:
    - event: ExecutionSuccess(bytes32 txHash, uint256 payment)

networks:
# - id: 10200
#   start_block: 2211707
#   contracts:
#   - name: Hub
#     address:
#     - 0xdbF22D4e8962Db3b2F1d9Ff55be728A887e47710
#   - name: PersonalCRC
#   - name: HubV2
#     address:
#     - 0xb80feeDfEce647dDc709777D5094fACD157BA001
#   - name: ERC20Lift
#     address:
#     - 0xBD2D6Fbb6A702B04B750Bc9942fBaAE81187355E
#   - name: StandardTreasury
#     address:
#     - 0xC06ADED7950429FdF2023e139B076f6BaFf9Fe1C
#   - name: NameRegistry
#     address:
#     - 0x24b3fDCdD9fef844fB3094ef43c0A6Ac23a6dF9E
#   - name: WrapperERC20Personal
- id: 100
  # start_block: 12529458
  start_block: 35732788
  contracts:
  - name: HubV2
    address:
    - 0xa5c7ADAE2fd3844f12D52266Cb7926f8649869Da
  - name: ERC20Lift
    address:
    - 0xB6B79BeEfd58cf33b298A456934554cf440354aD
  - name: StandardTreasury
    address:
    - 0xbb76CF35ec106c5c7a447246257dcfCB7244cA04
  - name: NameRegistry
    address:
    - 0x738fFee24770d0DE1f912adf2B48b0194780E9AD
  - name: WrapperERC20Personal
  - name: SafeAccount

rollback_on_reorg: false
